#!/usr/bin/env bash
PROGNAME=`basename $0`
VERSION="Version 1.0"

ST_OK=0
ST_WR=1
ST_CR=2
ST_UK=3

print_help() {
    echo "$PROGNAME $VERSION"
    echo ""
    echo "$PROGNAME is a Nagios plugin to check if the JOBTRACKER is Alive or Not"
    echo ""
    exit $ST_UK
}

while [ -n "$1" ]; do
	case "$1" in
		--help|-h)
			print_help
			exit $ST_UK
			;;
		*)
			echo "Unkown argument: $1"
			print_help
			exit $ST_UK
			;;
		esac
	shift
done

get_vals() {
  NS=`netstat -plten | grep -m1 "50030" | awk '{print $6}'`
	ST=`/etc/init.d/hadoop-0.20-mapreduce-jobtracker status | grep -m1 "running" | awk '{print $5}'`
}

do_output() {
	output="Resource Manager is : ${ST} and listing on the port 50030"
}

dont_output() {
	fail_output="Resource Manager is Dead and not listing on port 50030"
}

get_vals
do_output

if [ "$NS" = "LISTEN" -a "$ST" = "running..." ]
then
	echo "${output}"
	exit $ST_OK
else
	dont_output
	echo "${fail_output}"
	exit $ST_CR
fi